# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"


variables:
    # Workflow inputs given to nextflow.
    # The workflow should define `--out_dir`, the CI template sets this.
    # Only common file inputs and option values need to be given here
    # (not things such as -profile)
    NF_PROCESS_FILES: "subworkflows/local/input_check.nf"
    NF_WORKFLOW_OPTS: "--ubam test_data/porec_test.concatemers.bam --ref \
    test_data/porec_test.fasta --phased_vcf test_data/porec_test.phased_variants.vcf.gz \
    --mcool_resolutions 10,20,30 --cutter NlaIII \
    --vcf test_data/porec_test.phased_variants.vcf.gz --pairs \
    --chromunity --paired_end --filter_pairs --paired_end_minimum_distance 100 \
    --paired_end_maximum_distance 200"
    NF_IGNORE_PROCESSES: "chunk_ubam"
    CI_FLAVOUR: "new"

macos-run:
    tags:
        - macos
        - x86
        - oxford
