name: wf-pore-c2
channels:
  - epi2melabs
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8.*
  - typer>=0.6.1
  - pysam>=0.19.1
  - biopython>=1.79
  - polars>=0.13.62
  - attrs>=22.1.0
  - cattrs
  - mappy
  - epi2melabs
  - minimap2>=2.24
  - pairtools>=1.0.1
  - cooler>0.8.0
  - samtools*
  - whatshap>=1.6
  - mosdepth
  - d4tools
  - picard
  - pip:
      - "git+ssh://git@git.oxfordnanolabs.local/eharrington/pore-c2.git@0.7.0#egg=pore-c2"
